[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.10.1"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/ory/graceful"
  version = "0.1.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/ory/hydra"
  version = "1.0.0-beta.2"

[[constraint]]
  name = "github.com/ory/keto"
  version = "1.0.0-beta.2"

[[constraint]]
  name = "gopkg.in/mailgun/mailgun-go.v1"
